language: python
python:
  - 2.7
  - 2.6
before_install:
  - sudo apt-get update
  - sudo apt-get install swig
install:
  - pip install cython
  - pip install -r dev_requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - python setup.py develop
  # there is a circular dependency with codetools
  - pip install -e git+http://github.com/enthought/blockcanvas.git#egg=blockcanvas
script:
  - coverage run -m nose.core
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
