language: python
python:
  - 2.7
  - 2.6
before_install:
  - sudo apt-get update
  - sudo apt-get install swig
install:
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - coverage run -m nose.core
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
